# Generated by Django 5.2.7 on 2026-01-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
    ]
